# Recommened editor for this file: https://github.com/Microsoft/azure-pipelines-vscode
name: cargo
pool:
  vmImage:  $[ variables['HOST_IMAGE'] ]
strategy:
  matrix:
    x86_64-pc-windows-msvc:
      HOST_IMAGE: vs2017-win2016
      CHANNEL: stable
    x86_64-apple-darwin:
      HOST_IMAGE: macos-10.13
      CHANNEL: stable
    x86_64-unknown-linux-gnu_stable:
      HOST_IMAGE: ubuntu-16.04
      CHANNEL: stable
steps:
  # - powershell: Invoke-WebRequest -Uri https://win.rustup.rs/ -OutFile rustup-init.exe
  #   condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT'))
  # - script: |
  #     set TARGET=%SYSTEM_JOBDISPLAYNAME%
  #     rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
  #     set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  #     echo "##vso[task.setvariable variable=PATH;]%PATH%"
  #   condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT'))
  - bash: |
      export TARGET=$SYSTEM_JOBDISPLAYNAME
      curl https://sh.rustup.rs -sSf | sh -s -- -y--default-host $TARGET --default-toolchain $CHANNEL
      export PATH=$PATH:~/.cargo/bin
      echo "##vso[task.setvariable variable=PATH;]$PATH"
    # condition: and(succeeded(), ne(variables['Agent.OS'],'Windows_NT'))
  - bash: |
      rustc -V
      cargo -V
  - bash: |
      cargo install --git https://github.com/johnterickson/cargo2junit.git
  - bash: |
      cargo test -- -Z unstable-options --format json | tee test_results.json
      cat test_results.json
      cat test_results.json | cargo2junit > test_results.xml
  - task: PublishTestResults@2
    inputs: 
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test_results.xml'
