# Recommened editor for this file: https://github.com/Microsoft/azure-pipelines-vscode
name: cargo
pool:
  vmImage:  $(VM_IMAGE)
strategy:
  matrix:
    x86_64-pc-windows-gnu:
      TARGET: x86_64-pc-windows-gnu
      VM_IMAGE: vs2017-win2016
      CHANNEL: stable
    x86_64-pc-windows-msvc:
      TARGET: x86_64-pc-windows-msvc
      VM_IMAGE: vs2017-win2016
      CHANNEL: stable
    x86_64-apple-darwin:
      TARGET: x86_64-apple-darwin
      VM_IMAGE: macos-10.13
      CHANNEL: stable
    x86_64-unknown-linux-gnu:
      TARGET: x86_64-unknown-linux-gnu
      VM_IMAGE: ubuntu-16.04
      CHANNEL: stable
steps:
  - bash: |
      set -x
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
      echo "##vso[task.setvariable variable=PATH;]$PATH"
    displayName: Enusure rustup is installed
  - bash: |
      set -x
      rustup toolchain install --no-self-update $CHANNEL-$TARGET
      rustup default $CHANNEL-$TARGET
    displayName: Select toolchain
  - bash: |
      set -x
      rustup toolchain list
      rustc -V
      cargo -V
    displayName: Check rustc and cargo versions
  - bash: |
      cargo install cargo2junit
    displayName: Install cargo2junit
  - bash: |
      cargo build
    displayName: build
  - bash: |
      cargo test -- -Z unstable-options --format json | tee test_results.json
    displayName: run cargo test
  - bash: |
      cat test_results.json | cargo2junit > test_results_lkg.xml
    displayName: convert to junit using LKG cargo2junit
  - task: PublishTestResults@2
    inputs: 
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test_results_lkg.xml'
      testRunTitle: LKG_$(System.JobDisplayName)
      buildPlatform: LKG_$(System.JobDisplayName)
    condition: succeededOrFailed()
  - bash: |
      cat test_results.json | ./target/debug/cargo2junit > test_results.xml
    displayName: convert to junit using just-built cargo2junit
  - task: PublishTestResults@2
    inputs: 
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test_results.xml'
      testRunTitle: $(System.JobDisplayName)
      buildPlatform: $(System.JobDisplayName)
    condition: succeededOrFailed()
